### ISSUE TITLE
Minification is failing when using images

### ISSUE THREAD

**Issue by ktecho** [fedemartinm/lexical-minifier#2]
I'm using the minifier and packer from this utility, and it's mostly working fine, but when trying to pack editor content with images, it breaks. I've tried adding 2 paragraphs of texts, and it works flawlessly. The next test is adding an image after the 2 paragraphs. Minify seems like it works fine (look at the element 2):

![image](https://github.com/fedemartinm/lexical-minifier/assets/547169/74bac599-e5fa-406d-b3d9-bd940f78f5c9)

But after using packer, I get this:

![image](https://github.com/fedemartinm/lexical-minifier/assets/547169/57d1bfd4-9416-4ab1-bceb-dba2cd127f66)

If I try to unpack and unminify it again, the lexical editor will not load it, so I guess those 2 `undefined` are not correct, right?

**Comment by fedemartinm** [comment]
Hi @ktecho 
I have two comments about this issue:
-  I can confirm that the "image" type nodes are not being minified, and this is expected because it is not included in the built-in minifiers. I can add support for image minification, but I would like to know which plugin you are using to add images (I think it is probably `image` and `inline-image` from lexical-playground, but I would like to confirm).
- The packer output seems to be incorrect. Is there any chance you could share the serialized state of your editor here? (Unminified, just the JSON)

Thanks

**Comment by ktecho** [comment]
Hi @fedemartinm 

I'm using `svelte-lexical`, and the plugin is called `Image`, so I guess it's derived from the standard `lexical` package.

I think this is what you asked for?

```
{
    "root": {
        "children": [
            {
                "children": [
                    {
                        "detail": 0,
                        "format": 0,
                        "mode": "normal",
                        "style": "",
                        "text": "aaa",
                        "type": "text",
                        "version": 1
                    }
                ],
                "direction": "ltr",
                "format": "",
                "indent": 0,
                "type": "paragraph",
                "version": 1
            },
            {
                "children": [
                    {
                        "detail": 0,
                        "format": 0,
                        "mode": "normal",
                        "style": "",
                        "text": "bbb",
                        "type": "text",
                        "version": 1
                    }
                ],
                "direction": "ltr",
                "format": "",
                "indent": 0,
                "type": "paragraph",
                "version": 1
            },
            {
                "children": [
                    {
                        "altText": "Twitter",
                        "caption": {
                            "editorState": {
                                "root": {
                                    "children": [],
                                    "direction": null,
                                    "format": "",
                                    "indent": 0,
                                    "type": "root",
                                    "version": 1
                                }
                            }
                        },
                        "height": 0,
                        "maxWidth": 500,
                        "showCaption": false,
                        "src": "https://pbs.twimg.com/profile_banners/982621410299392000/1633517188/1080x360",
                        "type": "image",
                        "version": 1,
                        "width": 0
                    }
                ],
                "direction": null,
                "format": "",
                "indent": 0,
                "type": "paragraph",
                "version": 1
            }
        ],
        "direction": "ltr",
        "format": "",
        "indent": 0,
        "type": "root",
        "version": 1
    }
}
```

**Comment by fedemartinm** [comment]
This issue is an interesting case. On one hand, the Lexical documentation states that there's only one rootNode in an editorState: https://lexical.dev/docs/concepts/nodes#rootnode

However, it's common to encounter nested editors (for example, image captions), see:
https://github.com/umaranis/svelte-lexical/blob/master/packages/svelte-lexical/src/core/plugins/Image/ImageComponent.svelte#L244

I'll look for a solution to be able to minimize nested editors.

**Comment by ktecho** [comment]
Maybe that's a `svelte-lexical` only thing, not present in (react) lexical?

**Comment by ktecho** [comment]
@fedemartinm What needs to be done to merge that PR? Do you want me to test it in my code?

Thanks!

**Comment by fedemartinm** [comment]
@ktecho the latest published version should fix the error

**Comment by ktecho** [comment]
> @ktecho the latest published version should fix the error

It works perfectly now!! Thanks a lot @fedemartinm !!!
